"""create application tables

Revision ID: 4d5d68fbd1c8
Revises: 5ed9f89d1472
Create Date: 2026-09-09 21:03:24.235792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.database.utc_datetime import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = '4d5d68fbd1c8'
down_revision: Union[str, Sequence[str], None] = '5ed9f89d1472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('application_type', sa.String(length=50), nullable=False),
    sa.Column('date_applied', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('job_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column(
        'follow_up_at',
        UTCDateTime(),
        nullable=False,
    ),
    sa.Column('note', sa.String(length=2000), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', UTCDateTime(), nullable=False),
    sa.Column('interview_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    op.drop_table('follow_ups')
    op.drop_table('applications')
    op.drop_table('companies')
    # ### end Alembic commands ###
